# Generated by Django 6.0.2 on 2026-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('UNAUTH', 'Unauthorized Access'), ('POCKET', 'Hand-to-Pocket')], max_length=10)),
                ('confidence', models.FloatField()),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='alert_clips/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('blockchain_tx', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='POSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
