# Generated by Django 6.0.2 on 2026-02-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyalert',
            name='video_clip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
