# Generated by Django 6.0.2 on 2026-02-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0002_alter_anomalyalert_video_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('initial_cash', models.FloatField(default=0.0)),
                ('expected_cash', models.FloatField(default=0.0)),
                ('actual_cash', models.FloatField(default=0.0)),
                ('discrepancy', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='rule_violated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='safety_mode_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SafetyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=10)),
                ('linked_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.workshift')),
            ],
        ),
    ]
