# Generated by Django 6.0.2 on 2026-02-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0003_workshift_anomalyalert_rule_violated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poslog',
            name='payment_mode',
            field=models.CharField(default='CASH', max_length=20),
        ),
    ]
