# Generated by Django 6.0.2 on 2026-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0004_poslog_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('linked_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('anomaly_triggered', models.BooleanField(default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='tier_source',
            field=models.CharField(choices=[('VISUAL', 'Direct YOLO Vision'), ('POS_LOGIC', 'POS Log Heuristic'), ('TRAJECTORY', 'Side-Angle Trajectory'), ('IOT_SIM', 'Simulated IoT Sensor')], default='VISUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalyalert',
            name='anomaly_type',
            field=models.CharField(choices=[('UNAUTH', 'Unauthorized Access'), ('POCKET', 'Hand-to-Pocket'), ('DRAWER_NO_SALE', 'Drawer Opened Without Sale'), ('PROLONGED_OPEN', 'Drawer Open Too Long'), ('MISMATCH', 'POS Log Mismatch'), ('TRAJECTORY', 'Hand-to-Pocket Trajectory'), ('VIDEO_CLIP', 'Video Clip Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalyalert',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='anomalyalert',
            name='rule_violated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
